export const ROUTES = {
    Home: "/",
    Shop: "/shop",
    TypeFuels: "/typefuels",
    Login: "/login",
    Contact: "/contacts",
    Registration: "/registration",
    ProductDetails: "/details",
    HistoryFuels: "/user/historyfuels",
    Settings: "/user/settings",
    Cars: "/user/cars",
    Basket: "/user/basket",
    Fueling: "/fueling",
    ResetPassword: "/reset-password",
    AdminLogin: '/admin/login',
    CustomersDashboard:'/admin/customers',
    CustomersDetails: '/customers',
    CarsDashboard: '/admin/cars',
    CarsDetails: '/cars',
    ProductsDashboard: '/admin/products',
    AdminProductsDetails: '/products/details',
    AdminRequests: 'admin/requests',
    AdminFuelStation: 'admin/fuelstations',
    AdminFuelStationDetail: '/fuelstation',
    AdminFuelType: "admin/fueltype"
}