export const ROUTES = {
    Home: "/",
    Shop: "/shop",
    TypeFuels: "/typefuels",
    Login: "/login",
    Contact: "/contacts",
    Registration: "/registration",
    ProductDetails: "/details",
    HistoryFuels: "/user/historyfuels",
    Settings: "/user/settings",
    Cars: "/user/cars",
    Basket: "/user/basket",
    Fueling: "/fueling",
    ResetPassword: "/reset-password",
    AdminLogin: '/admin/login',
    CustomersDashboard:'/admin/customers',
    CustomersDetails: '/admin/customers',
    CarsDashboard: '/admin/cars',
    CarsDetails: '/admin/cars',
    ProductsDashboard: '/admin/products',
    AdminProductsDetails: '/admin/products/details',
    AdminRequests: '/admin/requests',
    AdminFuelStation: '/admin/fuelstations',
    AdminFuelStationDetail: '/fuelstation',
    AdminFuelType: '/admin/fueltype',
    AdminDashboard: '/admin',
    OperatorsDashboard: '/admin/operators',
    OperatorRequests: '/operator/requests',
    OperatorCars: '/operator/cars',
    OperatorProducts: '/operator/products',
    OperatorTypeFuels: '/operator/fueltype',
    OperatorFuelStation: '/operator/fuelstation',
    OperatorFuelStationDetail: '/operator/fuelstation'
}